# actuator endpoints
management:
  server:
    port: 8080
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure: 
        include: "*"
spring:
  main:
    web-application-type: SERVLET
    
# Kafka
# ${spring.emb}
kafka:
  broker:
    boostrap-servers: localhost:9092
  etl-subflow-example:
    producer:
      topic: subflow.out
    consumer:
      auto-offset-reset: earliest
      group-id: etl-subflow-example
      topic: subflow.in
    